# Generated by Django 5.2.2 on 2025-06-08 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(blank=True, help_text='한글 회사명', max_length=150, null=True)),
                ('name_en', models.CharField(blank=True, help_text='영문 회사명', max_length=300, null=True)),
                ('name_ja', models.CharField(blank=True, help_text='일본어 회사명', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='태그 이름', max_length=50, null=True)),
                ('number', models.IntegerField(help_text='태그 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('number',), name='unique_tag_number')],
            },
        ),
        migrations.CreateModel(
            name='CompanyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.tag')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(related_name='companies', through='company.CompanyTag', to='company.tag'),
        ),
        migrations.AddConstraint(
            model_name='companytag',
            constraint=models.UniqueConstraint(fields=('company', 'tag'), name='unique_company_tag'),
        ),
    ]
